# idle after 3min
CONFIG_ZMK_IDLE_TIMEOUT=180000
# sleep after 20min
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=1
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=1
# undeglow off after idle timeout (3min)
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=3264000

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
