CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=66
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
CONFIG_PROSPECTOR_MODIFIER_OS_GENERIC=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# sleep after 20min
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1200000

# turn off display after 15min of idle
CONFIG_PROSPECTOR_DISPLAY_SLEEP_ENABLE=y
CONFIG_PROSPECTOR_DISPLAY_IDLE_TIMEOUT_MS=900000
